const express=require('express')
const c=require('../controllers/Admin')
const upload=require('../middleware/upload')
const router=express.Router()
router.post('/login',c.login)
router.get('/stats',c.stats)
router.get('/products',c.products)
router.post('/products',upload.fields([{name:'thumbnail',maxCount:1},{name:'images',maxCount:5}]),c.createProduct)
router.put('/products/:id',c.updateProduct)
router.delete('/products/:id',c.deleteProduct)
router.get('/orders',c.orders)
router.get('/orders/:uuid',c.orderById)
router.patch('/orders/:uuid',c.updateOrder)
router.get('/coupons',c.coupons)
router.post('/coupons',c.createCoupon)
router.get('/audit',c.audit)
router.get('/reports/sales',c.reports)
router.get('/reports/sales.csv',c.reportsCsv)
module.exports=router
